name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Install Clojure CLI and Babashka
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 'latest'
          bb: 'latest'

      - name: Run CI Task
        run: clojure -T:build ci

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: clj-mergetool-${{ matrix.os }}-${{ matrix.arch }}
          path: target/clj-mergetool${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          if-no-files-found: error
